name: docker fail

on: push

jobs:
  test-regex:
    name: docker fail
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses:  docker/setup-buildx-action@v1
      id: issues
      with:
        regex_pattern: '([A-Z][A-Z0-9]+-[0-9]+)'
        regex_option: te
        search_string: 'this is a test'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1






