name: Testing regex match action original version

on: push

jobs:
  test-regex:
    name: Testing Regex GHA
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: MeilCli/regex-match@v1.5.0
      id: issues
      with:
        regex_pattern: '([A-Z][A-Z0-9]+-[0-9]+)'
        regex_option: te
        search_string: 'this is a test'

    - name: regex match action
      uses: MeilCli/regex-match@v1.0.1

